theme: jekyll-theme-minimal
title: Kurashicom Technology Group
description: <a href="./格活.md">格活</a>
logo: https://user-images.githubusercontent.com/29177665/48538087-d94b7500-e8f6-11e8-8564-211036a6cdd6.png
show_downloads: false
